---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: data
  label: Homepage
  create: all
  match: "**/*"
- type: heading
  label: GTM
- type: directory
  path: content/portfolio
  label: Templates
  create: all
  match: "**/*"
- type: heading
  label: Nosotros
- type: directory
  path: content/about
  label: Nosotros
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Blog Post
- type: directory
  path: content/blog
  label: Post
  create: documents
  match: "**/*"
  new_doc_ext: '20191203072044'
  templates:
  - post
- type: heading
  label: Data
- type: directory
  path: i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Contacto
- type: directory
  path: content/contact
  label: Contacto
  create: all
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: ''
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
